<?php

namespace Fwk\Events;

require_once __DIR__ .'/../Event.php';

/**
 * Test class for Event.
 * Generated by PHPUnit on 2010-12-22 at 14:22:34.
 */
class EventTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Event
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Event('test.event');
    }

    /**
     * @todo Implement testGetName().
     */
    public function testGetName()
    {
        $this->assertEquals('test.event', $this->object->getName());
    }

    /**
     */
    public function testGetData()
    {
        $this->assertTrue(is_array($this->object->getData()));
    }

    /**
     */
    public function testSetProcessed()
    {
        $this->assertFalse($this->object->isProcessed());
        $this->object->setProcessed(true);
        $this->assertTrue($this->object->isProcessed());
    }
}
